algoritmo "Dolar"
// Função :Converter valor de dólares para reais
// Autor :Kevyn marques Santana
// Data : 09/03/2023
// Seção de Declarações 
var
  dolar,reais,cot:real
inicio
//entrada
escreval("escreva aqui o valor em dólares: ")
leia(dolar)
//processamento
cot<-5.12
reais<-dolar/cot
//saida
escreval("-----RESULTADO-----")
escreval("o seu valor é: R$ ",reais)



// Seção de Comandos 
fimalgoritmo
