algoritmo "Fahreinheit"
// Função :Quantidade de combustivel utilizado por KM
// Autor :Kevyn Marques Santana
// Data : 09/03/2023
// Seção de Declarações
var
C,F: real
inicio
// Seção de Comandos
//inicio
escreval("Escreva a temperatura em graus celsius: ")
leia(C)

//processo
F<-(9*C+160)/5


//saida
escreval("--------------RESULTADO----------------")
escreval(C,"°C convertido para Fahreinheit é: " ,F,"°F")
fimalgoritmo
