algoritmo "Numero"
// Função :Numero
// Autor :Kevyn Maruqes Santana
// Data : 25/05/2023
// Seção de Declarações
var
 men:caractere
inicio
// Seção de Comandos
//Entrada

escreval("Sua menção no bimestre:")
leia(men)

//Processamento

se((men="I") e (men="R")) entao
 escreval("Você foi reprovado:(")
 senao
 escreval("Você passou:D")
 fimse
 se((men<>"I")e(men<>"R")e(men<>"B")e(men<>"MB")) entao
  escreval("A menção que você digitou é invalida")
 fimse


fimalgoritmo
