algoritmo "Salario"
// Função :Calcular se o salario de um usuario e maior que seus gastos
// Autor : Kevyn Marques Santana
// Data : 18/05/2023
// Seção de Declarações 
var
   num:real
inicio
// Seção de Comandos 

//Entrada

escreval("Digite um numero aleátorio:")
leia(num)

//Processamento

se (num>=10) entao
   escreval(num, " é maior que 10 :D")
senao
     escreval("putz:/")
fimse

fimalgoritmo
