algoritmo "Numero"
// Função :Numero
// Autor :Kevyn Maruqes Santana
// Data : 25/05/2023
// Seção de Declarações
var
 num:real
inicio
// Seção de Comandos
//Entrada

escreval("Digite um numero aleatorio: ")
leia(num)

//Processamento

se((num>100) e (num<200)) entao
 escreval(num," esta entre 100 e 200")
 senao
 escreval(num," não esta entre 100 e 200")
 fimse


fimalgoritmo
